/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeedRouteImport } from './routes/$seed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeedUsernameRouteImport } from './routes/$seed/$username'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SeedRoute = SeedRouteImport.update({
  id: '/$seed',
  path: '/$seed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedUsernameRoute = SeedUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => SeedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$seed': typeof SeedRouteWithChildren
  '/$seed/$username': typeof SeedUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$seed': typeof SeedRouteWithChildren
  '/$seed/$username': typeof SeedUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$seed': typeof SeedRouteWithChildren
  '/$seed/$username': typeof SeedUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$seed' | '/$seed/$username' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$seed' | '/$seed/$username' | '/api/auth/$'
  id: '__root__' | '/' | '/$seed' | '/$seed/$username' | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SeedRoute: typeof SeedRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$seed': {
      id: '/$seed'
      path: '/$seed'
      fullPath: '/$seed'
      preLoaderRoute: typeof SeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$seed/$username': {
      id: '/$seed/$username'
      path: '/$username'
      fullPath: '/$seed/$username'
      preLoaderRoute: typeof SeedUsernameRouteImport
      parentRoute: typeof SeedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SeedRouteChildren {
  SeedUsernameRoute: typeof SeedUsernameRoute
}

const SeedRouteChildren: SeedRouteChildren = {
  SeedUsernameRoute: SeedUsernameRoute,
}

const SeedRouteWithChildren = SeedRoute._addFileChildren(SeedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SeedRoute: SeedRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
